package definitions

const INVALID_REQUEST_ERROR = "INVALID_REQUEST_ERROR"
const RESOURCE_NOT_FOUND_ERROR = "RESOURCE_NOT_FOUND_ERROR"
const ACCESS_DENIED_ERROR = "ACCESS_DENIED_ERROR"
const SERVER_ERROR = "SERVER_ERROR"